### ISSUE TITLE
Does this still work?

### ISSUE THREAD

**Issue by kaleidawave** [JamesClonk/minecraft-server-app#1]
How does one use it?

**Comment by JamesClonk** [comment]
Yes it still works, I have a personal Minecraft server currently running on CF through this.

It's basically a wrapper around the Minecraft server itself. You'll need to have an S3 service bound to the app named `world-backup` (see https://github.com/JamesClonk/minecraft-server-app/blob/master/manifest.yml#L12), so it can automatically backup & download the world save.
There's a Makefile in the project that control various build steps that are required to be run (https://github.com/JamesClonk/minecraft-server-app/blob/master/Makefile)
- `scripts/setup.sh` will download all the necessary components
- `make build` packages everything up into the final jar file
- with `make run` you can run that jar file locally for testing
- with `make deploy` it will try to push the jar file onto CF and run it here
It needs to have a CF installation that supports TCP-routing obviously, as the Minecraft server speaks "raw" TCP.

**Comment by kaleidawave** [comment]
So I guess you cannot deploy it on bluemix due to TCP?

**Comment by JamesClonk** [comment]
If Bluemix does not have TCP-routing enabled then no, it will not work unfortunately.
